### ISSUE TITLE
Missing required positional argument when generating OTP

### ISSUE THREAD

**Issue by raffaem** [andry08/ArubaOTP-seed-extractor#15]
```
$ python ./scripts/main.py generate
Traceback (most recent call last):
  File "./scripts/main.py", line 90, in main
    generate(args.seed, args.time)
  File "./scripts/main.py", line 33, in generate
    code = otputil.generate_totp(seed, time)
TypeError: generate_totp() missing 2 required positional arguments: 'interval' and 'time'
```

**Comment by andry08** [comment]
Grazie del report, ora dovrebbe funzionare.
