### ISSUE TITLE
Problem executing script

### ISSUE THREAD

**Issue by g3n10z** [andry08/ArubaOTP-seed-extractor#6]
I'm tring with python 3.6

 python3 ./scripts/main.py extract 346702100501561100
Traceback (most recent call last):
  File "./scripts/main.py", line 85, in <module>
    main()
  File "./scripts/main.py", line 44, in main
    description='What do you want to do?')
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

What python version is made this script for?
thanks

**Comment by andry08** [comment]
Should be fixed now. Let us know if you have other issues.
