### ISSUE TITLE
Error During of the validation of the Seed

### ISSUE THREAD

**Issue by alpesm** [andry08/ArubaOTP-seed-extractor#8]
Good moring,
i'm experiencing this error:

Traceback (most recent call last):
  File "./scripts/main.py", line 95, in main
    extract(args.activation_code, args.only_output, args.show_qr)
  File "./scripts/main.py", line 23, in extract
    seed = extractor.extract_otp(activation_code)
  File "/root/ArubaOTP-seed-extractor/scripts/request.py", line 44, in extract_otp
    raise Exception('Error occured in seed validation: [{}] {}'.format(resp2['returncode'], resp2['description']))
Exception: Error occured in seed validation: [0005] Validazione licenza fallita sync non riuscito

I've tryed checking the requirement and tried to reinstall the script but is not working.. any suggestion?

**Comment by ale-saglia** [comment]
I'm getting the same error even after the fix
Traceback (most recent call last):
  File "./scripts/main.py", line 95, in main
    extract(args.activation_code, args.only_output, args.show_qr)
  File "./scripts/main.py", line 23, in extract
    seed = extractor.extract_otp(activation_code)
  File "/home/alessandro/ArubaOTP-seed-extractor/scripts/request.py", line 44, in extract_otp
    raise Exception('Error occured in seed validation: [{}] {}'.format(resp2['returncode'], resp2['description']))
Exception: Error occured in seed validation: [0005] Validazione licenza fallita sync non riuscito

Don't know if they changed the system again
